sernasistemas/Models/HistoriaClinica.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SernaSistemas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaClinica
    {
        public int Id { get; set; }
        public int IdPaciente { get; set; }
        public int IdMedico { get; set; }
        public System.DateTime FechaHistoria { get; set; }
        public string MotivoConsulta { get; set; }
        public string Analisis { get; set; }
        public string ImpresionDiagnostica { get; set; }
        public string PlanTerapeutico { get; set; }
    }
}

sernasistemas/Models/ListaHistorias.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WCFClinica.Modelos;

namespace SernaSistemas.Models {
    public class ListaHistorias {
        public List<selHistoriaReqResp> Historias { get; set; }
    }
    public class buscarHistoriasModel {
        public List<buscarHistoriasItem> Historias { get; set; }
    }
}

sernasistemas/Models/ListaPacientes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WCFClinica.Modelos;

namespace SernaSistemas.Models {
    public class ListaPacientesModel {
        public int IdMedico { get; set; }
        public buscarPacienteResponse Pacientes { get; set; }
    }
}

sernasistemas/Models/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WCFClinica.Modelos;

namespace SernaSistemas.Models {
    public class LoginModel {
        public LoginRequest Request { get; set; }
    }
}

sernasistemas/Models/NotaEvolutiva.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WCFClinica.Modelos;

namespace SernaSistemas.Models {
    public class NotaEvolutivaModel {
        public int IdNota { get; set; }
        public int IdHistoria { get; set; }
        public int IdPaciente { get; set; }
        public DateTime Fecha { get; set; }
        public string NombrePaciente { get; set; }
        public string MotivoConsulta { get; set; }
        public string Plan { get; set; }
        /// <summary>
        /// El contenido de esta propiedad no va hacia la tabla de Exploración física, sino a la de
        /// notas evolutivas
        /// </summary>
        public RegistraExploraFisicaReqResp ExploracionFisica { get; set; }
        public string PlanTratamiento { get; set; }
    }
}

sernasistemas/Models/agendaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SernaSistemas.Models
{
    public class agendaViewModel
    {
    }
}

sernasistemas/Controllers/HistoriaClinicaController.cs
using Microsoft.ReportingServices.Interfaces;
using SernaSistemas.Models;
using SernaSistemas.Models.Assemblers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WCFClinica;
using WCFClinica.Clases;
using WCFClinica.Modelos;
using WCFSernaSistemasLib;

namespace SernaSistemas.Controllers
{
    public class HistoriaClinicaController : Controller
    {
        private static WCFClinica.Modelos.CatalogoReqResp obtenerCatalogo(string catalogo)
        {
            WCFClinica.ClinicaService _servicio = new WCFClinica.ClinicaService();
            var resutados = _servicio.obtenerCatalogo(new WCFClinica.Modelos.CatalogoReqResp()
            {
                Catalogo = catalogo
            });
            return resutados;
        }

        // GET: HistoriaClinica
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult postPago()
        {
            //SernaSistemasServices servicio = new SernaSistemasServices();
            //var response = servicio.registrarContacto(new ContactoRequest()
            //{
            //    Nombre = "Nuevo registro médico",
            //    Telefono = string.Empty,
            //    eMail = "efrain@sernasis.com",
            //    Comentario = "Revisa tu cuenta de Paypal para ver el pago hecho",
            //    FechaContacto = DateTime.Today,
            //    Id = 0
            //});
            //if (response.tieneError)
            //    return View();
            return View();
        }
        public ActionResult Login()
        {
            var model = new LoginModel()
            {
                Request = new WCFClinica.Modelos.LoginRequest()
            };
            return View("_login");
        }
        [HttpPost]
        public RedirectToRouteResult hazLogin(LoginModel model)
        {
            WCFClinica.ClinicaService servicio = new WCFClinica.ClinicaService();
            var response = servicio.hazLogin(new WCFClinica.Modelos.LoginRequest()
            {
                Usuario = model.Request.Usuario,
                Password = model.Request.Password
            });
            if (response.Resultado == 1)
            {
                var modelvista = new buscarHistoriasModel();
                Session.Remove("UsrHC");
                Session.Remove("UsrKey");
                Session.Remove("UsrHCId");
                Session.Add("UsrHC", model.Request.Usuario);
                Session.Add("UsrKey", response.Mensaje);
                Session.Add("UsrHCId", response.Id);
                return RedirectToAction("BuscarHistorias");
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
        public ActionResult verPaciente(int IdPaciente)
        {
            if (Session["UsrHC"] == null)
                return RedirectToAction("Login");
            if (string.IsNullOrEmpty(Session["UsrHC"].ToString()))
            {
                return RedirectToAction("Login");
            }
            WCFClinica.ClinicaService servicio = new WCFClinica.ClinicaService();
            var response = servicio.selPaciente(new WCFClinica.Modelos.selPacienteReqResp()
            {
                IdPaciente = IdPaciente
            });
            var tiposexo = obtenerCatalogo("Sexo");
            var tiposangre = obtenerCatalogo("TipoSangre");
            var tipotelefono = obtenerCatalogo("TipoTelefono");
            var Estados = servicio.obtenerEstados(new WCFClinica.Modelos.EstadosReqResp() { Datos = new WCFClinica.Modelos.EstadosReqRespItem() { Nombre = string.Empty, Id = 0 } });

            PacienteModel modelo = new PacienteModel()
            {
                Alcohol = response.Alcohol,
                CiudadNacimiento = response.CiudadNacimiento,
                CiudadResidencia = response.CiudadResidencia,
                dicTipoTelefono = tipotelefono.items.Select(i => new SelectListItem { Text = i.Value, Value = i.Key.ToString() }),
                dicTipoSangre = tiposangre.items.Select(i => new SelectListItem { Text = i.Value, Value = i.Key.ToString() }),
                dicSexo = tiposexo.items.Select(i => new SelectListItem { Text = i.Value, Value = i.Key.ToString() }),
                dicLugarResidencia = Estados.Items.Select(i => new SelectListItem { Text = i.Nombre, Value = i.Id.ToString() }),
                Domicilio = response.Domicilio,
                ErrNum = response.ErrNum,
                FechaNacimiento = response.FechaNacimiento,
                IdLugarNacimiento = response.IdLugarNacimiento,
                IdLugarResidencia = response.IdLugarResidencia,
                IdPaciente = response.IdPaciente,
                IdPersona = response.IdPersona,
                IdSexo = response.IdSexo,
                IdTipoSangre = response.IdTipoSangre,
                IdTipoNumero = response.IdTipoNumero,
                LugarNacimiento = response.LugarNacimiento,
                LugarResidencia = response.LugarResidencia,
                Mensaje = response.Mensaje,
                Nombre = response.Nombre,
                Numero = response.Numero,
                Rh = response.Rh,
                Sexo = response.Sexo,
                Tabaco = response.Tabaco,
                tieneError = response.tieneError,
                TipoSangre = response.TipoSangre,
                AnioResidencia = response.AnioResidencia,
                Ocupacion = response.Ocupacion
            };
            return View("_Paciente", modelo);
        }
        public ActionResult Paciente(PacienteModel model)
        {
            if (Session["UsrHC"] == null)
                return RedirectToAction("Login");
            if (string.IsNullOrEmpty(Session["UsrHC"].ToString()))
            {
                return RedirectToAction("Login");
            }
            WCFClinica.ClinicaService servicio = new WCFClinica.ClinicaService();
            if (model == null)
                model = new PacienteModel();

            var tiposexo = obtenerCatalogo("Sexo");
            var tiposangre = obtenerCatalogo("TipoSangre");
            var tipotelefono = obtenerCatalogo("TipoTelefono");
            var Estados = servicio.obtenerEstados(new WCFClinica.Modelos.EstadosReqResp() { Datos = new WCFClinica.Modelos.EstadosReqRespItem() { Nombre = string.Empty, Id = 0 } });

            model.dicTipoTelefono = tipotelefono.items.Select(i => new SelectListItem { Text = i.Value, Value = i.Key.ToString() });
            model.dicTipoSangre = tiposangre.items.Select(i => new SelectListItem { Text = i.Value, Value = i.Key.ToString() });
            model.dicSexo = tiposexo.items.Select(i => new SelectListItem { Text = i.Value, Value = i.Key.ToString() });
            model.dicLugarResidencia = Estados.Items.Select(i => new SelectListItem { Text = i.Nombre, Value = i.Id.ToString() });
            return View("_paciente", model);
        }
        [HttpPost]
        public ActionResult postPaciente(PacienteModel modelo)
        {
            if (Session["UsrHC"] == null)
                return RedirectToAction("Login");
            if (string.IsNullOrEmpty(Session["UsrHC"].ToString()))
            {
                return RedirectToAction("Login");
            }

            WCFClinica.ClinicaService servicio = new WCFClinica.ClinicaService();
            modelo.dicSexo = obtenerCatalogo("Sexo").items.Select(i => new SelectListItem { Text = i.Value, Value = i.Key.ToString() });
            modelo.dicTipoSangre = obtenerCatalogo("TipoSangre").items.Select(i => new SelectListItem { Text = i.Value, Value = i.Key.ToString() });
            modelo.dicTipoTelefono = obtenerCatalogo("TipoTelefono").items.Select(i => new SelectListItem { Text = i.Value, Value = i.Key.ToString() });

            var request = new WCFClinica.Modelos.RegistraPacienteReqResp()
            {
                Alcohol = modelo.Alcohol,
                CiudadNacimiento = modelo.CiudadNacimiento,
                CiudadResidencia = modelo.CiudadResidencia,
                Domicilio = modelo.Domicilio,
                FechaNacimiento = modelo.FechaNacimiento,
                IdPaciente = modelo.IdPaciente,
                IdPersona = modelo.IdPersona,
                LugarNacimiento = modelo.LugarNacimiento,
                LugarResidencia = modelo.LugarResidencia,
                Nombre = modelo.Nombre,
                Rh = modelo.Rh,
                IdSexo = modelo.IdSexo,
                Tabaco = modelo.Tabaco,
                IdLugarNacimiento = modelo.IdLugarNacimiento,
                IdLugarResidencia = modelo.IdLugarResidencia,
                IdTipoSangre = modelo.IdTipoSangre,
                IdTipoNumero = modelo.IdTipoNumero,
                Numero = modelo.Numero,
                AnioResidencia = modelo.AnioResidencia,
                Ocupacion = modelo.Ocupacion
            };
            var response = servicio.registraPaciente(request);
            return RedirectToAction("Paciente", modelo);
        }
        /// <summary>
        /// con IdHistoria abre esa historia
        /// con IdPaciente crea nueva historia para ese paciente
        /// sin Ids crea nueva historia
        /// con Ids abre la historia
        /// </summary>
        /// <param name="IdHistoria"></param>
        /// <param name="idPaciente"></param>
        /// <returns></returns>
        public ActionResult Historia(int? IdHistoria, int? idPaciente)
        {
            if (Session["UsrHC"] == null)
                return RedirectToAction("Login");
            if (string.IsNullOrEmpty(Session["UsrHC"].ToString()))
            {
                return RedirectToAction("Login");
            }

            ClinicaService servicio = new ClinicaService();
            var Estados = servicio.obtenerEstados(new EstadosReqResp() { Datos = new EstadosReqRespItem() { Nombre = string.Empty, Id = 0 } });

sernasistemas/Views/HistoriaClinica/Index.cshtml
@{
    ViewBag.Title = "Index";
    ViewBag.vista = "Index";
    Layout = "~/Views/Shared/_LayoutClinica.cshtml";
}

<h2 class="text-center">Historias cl&iacute;nicas</h2>

<div class="row">
    <div class="col-md-5">
        <ul>
            <li>Inicia sesi&oacute;n desde cualquier dispositivo.</li>
            <li>Registra tus pacientes y b&uacute;scalos.</li>
            <li>Registra las historias cl&iacute;nicas para pacientes ya registrados o nuevos.</li>
            <li>Busca las historias que hayas registrado y rev&iacute;asalas o actual&iacute;zalas.</li>
            <li>Consulta y actualiza la informaci&oacute;n de tu perfil.</li>
            <li>Agrega notas evolutivas a cada historia y consúltalas cuando necesites.</li>
            <li>Exporta las historias y notas que hayas registrado como PDF.</li>
        </ul>
        @if (Session["UsrHc"] == null)
        {
            <div style="text-align:center;">
                @Html.ActionLink("Iniciar sesión", "Login", "HistoriaClinica", new { @class = "btn btn-lg btn-success", style = "box-shadow:#203016 0px 5px 5px;" })
            </div>
            <div class="card bg-info text-center">
                <h3 class="text-primary">Usuario y contraseña demo:</h3>
                <h4 class="text-primary"><strong>admin</strong></h4>
            </div>
        }
        &nbsp;
    </div>
    <div class="col-md-2">

    </div>
    <div class="col-md-5">
        @if (Session["UsrHc"] == null)
        {
            <div class="w-10 containerClinica">
                <p>
                    No requieres cuenta. Y en todo caso, PayPal te permite crear una sin necesidad que tengas saldo en ella y pagar con tu tarjeta. <br />
                    Es totalmente seguro. Se te redirige a la plataforma de PayPal (en la barra de direcciones en tu navegador ver&aacute;s el <em>https</em> y un candado).
                </p>
                <p>
                    <ol>
                        <li>Escribe tu nombre como referencia y registra tu pago.</li>
                        <li>En el formulario de Paypal que se abrirá, en el campo de descripción escribe tu correo electrónico.</li>
                        <li>Continúa registrando la información requerida para el pago y crea tu cuenta. No necesitas agregar saldo y Paypal no te aplicará cargos extra.</li>
                    </ol>
                </p>
                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" class="form-group">
                    <input type="hidden" name="cmd" value="_s-xclick">
                    <input type="hidden" name="hosted_button_id" value="J5K4JNGG2955S">
                    <table class="table">
                        <tr><td><input type="hidden" name="on0" value="Vigencias">Vigencias</td></tr>
                        <tr>
                            <td>
                                <select name="os0" class="form-control">
                                    <option value="3 meses">3 meses $100.00 MXN</option>
                                    <option value="6 meses">6 meses $190.00 MXN</option>
                                    <option value="12 meses">12 meses $360.00 MXN</option>
                                </select>
                            </td>
                        </tr>
                        <tr><td><input type="hidden" name="on1" value="Nombre (referencia)">Tu nombre (referencia)</td></tr>
                        <tr><td><input type="text" name="os1" maxlength="200" class="form-control form-text"></td></tr>
                    </table>
                    <input type="hidden" name="currency_code" value="MXN">
                    <input type="image" src="https://www.paypalobjects.com/es_XC/MX/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal, la forma más segura y rápida de pagar en línea.">
                    <img alt="" border="0" src="https://www.paypalobjects.com/es_XC/i/scr/pixel.gif" width="1" height="1">
                </form>

            </div>
        }
    </div>
</div>

sernasistemas/Views/HistoriaClinica/_Agenda.cshtml
@model SernaSistemas.Models.agendaViewModel

@{
    ViewBag.Title = "Agenda";
    ViewBag.vista = "_Agenda";
    Layout = "~/Views/Shared/_LayoutClinica.cshtml";
}

<h2>
    @ViewBag.Title
</h2>
@using (Html.BeginForm("postAgenda", "HistoriaClinica", FormMethod.Post))
{
    <div class="container containerClinica">
        <div class="row">
        </div>
    </div>

    <h3>&nbsp;</h3>
    <div class="row">
        <div class="col-md-12" style="text-align:center;">
            <button type="submit" class="btn btn-lg btn-success" style="box-shadow:#203016 0px 5px 5px;" data-toggle="tooltip"
                    data-placement="bottom" title="Guarda Nota evolutiva">
                <span class="glyphicon glyphicon-floppy-saved"></span> Guardar
            </button>
        </div>
    </div>
}

sernasistemas/Views/HistoriaClinica/_buscarHistorias.cshtml
@model SernaSistemas.Models.buscarHistoriasModel

@{
    ViewBag.Title = "Buscar historias";
    ViewBag.vista = "_buscarHistorias";
    Layout = "~/Views/Shared/_LayoutClinica.cshtml";
}

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("BuscarHistorias", "HistoriaClinica")) {
    <div class="container containerClinica">
        <div class="row">
            <div class="col-md-1">
                Paciente
            </div>
            <div class="col-md-6">
                @Html.TextBox(name: "txtBuscar", value: null, htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="col-md-2">
                Fecha de historia
            </div>
            <div class="col-md-2">
                <input type="date" name="txtFecha" id="txtFecha" class="form-control" value="2000-01-01" />
            </div>
            <div class="col-md-1">
                <button type="submit" class="btn btn-warning"><span class="glyphicon glyphicon-search"></span></button>
            </div>
        </div>
    </div>
}
<h3>&nbsp;</h3>

<table class="table table-bordered table-responsive">
    <thead>
        <tr>
            <th></th>
            <th>Paciente</th>
            <th>Motivo de consulta</th>
            <th>Fecha</th>
        </tr>
    </thead>
    @foreach (var item in Model.Historias) {
        <tr class="d-sm-table-row">
            <td class="d-sm-table-cell">
                @Html.ActionLink(" ", "Historia", new { IdHistoria = item.Id, IdPaciente = item.IdPaciente }, new { @class = "btn btn-info glyphicon glyphicon-open-file", style = "box-shadow:#203016 0px 5px 5px;" })
            </td>
            <td>
                @item.Paciente
            </td>
            <td class="d-sm-table-cell">
                @if (item.MotivoConsulta.Length > 200) {
                    <span>@item.MotivoConsulta.Substring(0, 200)</span>
                } else {
                    <span>@item.MotivoConsulta </span>
                }
            </td>
            <td>
                @item.FechaHistoria
            </td>
        </tr>
    }
</table>

sernasistemas/Views/HistoriaClinica/_listaHistorias.cshtml
@model SernaSistemas.Models.ListaHistorias

@{
    ViewBag.Title = "Lista de historias";
    ViewBag.vista = "_listaHistorias";
    Layout = "~/Views/Shared/_LayoutClinica.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("ListadoHistorias", "HistoriaClinica")) {
    <div class="container containerClinica">
        <div class="row">
            <div class="col-md-1">
                Paciente
            </div>
            <div class="col-md-10">
                @Html.TextBox(name: "txtBuscar", value: null, htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="col-md-1">
                <input type="submit" class="btn btn-warning" value="Buscar" />
            </div>
        </div>
    </div>
}
<h3>&nbsp;</h3>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Número</th>
            <th>Paciente</th>
            <th>Motivo de consulta</th>
        </tr>
    </thead>
    @foreach (var item in Model.Historias) {
        <tr class="d-sm-table-row">
            <td class="d-sm-table-cell">
                @item.Id
            </td>
            <td class="d-sm-table-cell">
                @item.IdPaciente
            </td>
            <td class="d-sm-table-cell">
                @item.MotivoConsulta
            </td>
        </tr>
    }
</table>

sernasistemas/Views/HistoriaClinica/_listaPacientes.cshtml
@model SernaSistemas.Models.ListaPacientesModel

@{
    ViewBag.Title = "Buscar pacientes";
    ViewBag.vista = "_listaPacientes";
    Layout = "~/Views/Shared/_LayoutClinica.cshtml";
}

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("ListadoPacientes", "HistoriaClinica")) {
    <div class="container containerClinica">
        <div class="row">
            <div class="col-md-1">
                Paciente
            </div>
            <div class="col-md-10">
                @Html.TextBox(name: "txtBuscar", value: null, htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="col-md-1">
                <button type="submit" class="btn btn-warning" value="Buscar"><span class="glyphicon glyphicon-search"></span></button>
            </div>
        </div>
    </div>
}
<h3>&nbsp;</h3>
<table class="table table-bordered table-responsive">
    <thead>
        <tr>
            <th></th>
            <th>Paciente</th>
            <th>Sexo</th>
            <th>Tipo de sangre</th>
            <th>Teléfono</th>
        </tr>
    </thead>
    @if (Model.Pacientes.Items != null) {
        foreach (var item in Model.Pacientes.Items) {
            <tr class="d-sm-table-row">
                <td class="d-sm-table-cell">
                    <div class="btn-group">
                        @Html.ActionLink(" ", "verPaciente", new { IdPaciente = item.IdPaciente }, new { @class = "btn btn-info glyphicon glyphicon-list-alt", style = "box-shadow:#203016 -2px 5px 5px;" })
                        @Html.ActionLink(" ", "Historia", new { IdPaciente = item.IdPaciente }, new { @class = "btn btn-success glyphicon glyphicon-check", style = "box-shadow:#203016 2px 5px 5px;" })
                    </div>
                </td>
                <td class="d-sm-table-cell">
                    @item.Nombre
                </td>
                <td class="d-sm-table-cell">
                    @item.Sexo
                </td>
                <td class="d-sm-table-cell">
                    @item.TipoSangre
                </td>
                <td class="d-sm-table-cell">
                    @item.NumeroTelefono
                </td>
            </tr>
        }
    }
</table>

sernasistemas/Views/HistoriaClinica/_login.cshtml
@model SernaSistemas.Models.LoginModel

@{
    ViewBag.Title = "Iniciar sesión";
    ViewBag.vista = "_login";
    Layout = "~/Views/Shared/_LayoutClinica.cshtml";
}

@using (Html.BeginForm("hazLogin","HistoriaClinica")) {
<div class="container card containerClinica" style="margin:auto; width:50%; padding-left:1em; padding-right:1em;">

    <div class="row card-header" style="padding-left:1em;">
        <h2>@ViewBag.Title</h2>
    </div>

    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                @Html.DisplayNameFor(m => m.Request.Usuario)
                @Html.TextBoxFor(m => m.Request.Usuario, new { @class = "form-control" })
                @Html.DisplayNameFor(m => m.Request.Password)
                @Html.PasswordFor(m => m.Request.Password, new { @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="card-footer">
        <div class="row">
            <div class="col-md-6 offset-3">
                <input type="submit" value="Iniciar sesión" class="btn btn-primary"/>
            </div>
        </div>
    </div>
</div>
}
<script>
    $(document).ready(function () {
        $("#Request_Usuario").focus();
    });
</script>

sernasistemas/Views/HistoriaClinica/_medico.cshtml
@model SernaSistemas.Models.MedicoModel

@{
    ViewBag.Title = "Información del médico";
    ViewBag.vista = "_medico";
    Layout = "~/Views/Shared/_LayoutClinica.cshtml";
}

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("postMedico", "HistoriaClinica")) {
    <div class="container containerClinica">
        @Html.HiddenFor(m => m.Perfil.Id, Model.Perfil.Id.ToString())

        <div class="row">
            <div class="col-md-2">
                @Html.DisplayNameFor(m => m.Perfil.Nombre)
            </div>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Perfil.Nombre, Model.Perfil.Nombre, new { @class = "form-control" })
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                @Html.DisplayNameFor(m => m.Perfil.Usuario)
            </div>
            <div class="col-md-4">
                @Html.TextBoxFor(m => m.Perfil.Usuario, Model.Perfil.Usuario, new { @class = "form-control" })
            </div>
            <div class="col-md-2">
                @Html.DisplayNameFor(m => m.Perfil.Constrasenia)
            </div>
            <div class="col-md-4">
                @Html.PasswordFor(m => m.Perfil.Constrasenia, new { @class = "form-control" })
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                @Html.DisplayNameFor(m => m.Perfil.FechaNacimiento)
            </div>
            <div class="col-md-2">
                @Html.TextBoxFor(m => m.Perfil.FechaNacimiento, Model.Perfil.FechaNacimiento.ToShortDateString(), new { @class = "form-control" })
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                @Html.DisplayNameFor(m => m.Perfil.IdLugarNacimiento)
            </div>
            <div class="col-md-4">
                @Html.DropDownListFor(m => m.Perfil.IdLugarNacimiento, Model.dicLugar, new { @class = "form-control" })
            </div>
            <div class="col-md-2">
                @Html.DisplayNameFor(m => m.Perfil.CiudadNacimiento)
            </div>
            <div class="col-md-4">
                @Html.TextBoxFor(m => m.Perfil.CiudadNacimiento, Model.Perfil.CiudadNacimiento, new { @class = "form-control" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.DisplayNameFor(m => m.Perfil.Sexo)
            </div>
            <div class="col-md-2">
                <div class="row">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.Perfil.Sexo, Model.dicSexo.First().Text.Substring(0, 3))
                    </div>
                    <div class="col-md-3">
                        @Html.RadioButtonFor(m => m.Perfil.Sexo, Model.dicSexo.First().Value, new { @class = "form-control" })
                    </div>
                    <div class="col-md-3">
                        @Html.LabelFor(m => m.Perfil.IdSexo, Model.dicSexo.Last().Text.Substring(0, 3))
                    </div>
                    <div class="col-md-3">
                        @Html.RadioButtonFor(m => m.Perfil.IdSexo, Model.dicSexo.Last().Value, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                @Html.DisplayNameFor(m => m.Perfil.IdTipoSangre)
            </div>
            <div class="col-md-2">
                @Html.DropDownListFor(m => m.Perfil.IdTipoSangre, Model.dicTipoSangre, new { @class = "form-control" })
            </div>
            <div class="col-md-2">
                @Html.DisplayNameFor(m => m.Perfil.Rh)
            </div>
            <div class="col-md-2">
                @Html.TextBoxFor(m => m.Perfil.Rh, Model.Perfil.Rh.ToString(), new { @class = "form-control" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-5">
            </div>
            <div class="col-md-2">
                <button type="submit" class="btn btn-lg btn-success" style="box-shadow:#203016 0px 5px 5px;"><span class="glyphicon glyphicon-floppy-saved"></span> Guardar</button>
            </div>
        </div>
    </div>
}